In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

In [3]:
df = pd.read_csv("D:\house price dataset\house pred data\House_Rent_Dataset.csv")

In [4]:
df

Posted On  BHK   Rent  Size            Floor    Area Type  \
0     2022-05-18    2  10000  1100  Ground out of 2   Super Area   
1     2022-05-13    2  20000   800       1 out of 3   Super Area   
2     2022-05-16    2  17000  1000       1 out of 3   Super Area   
3     2022-07-04    2  10000   800       1 out of 2   Super Area   
4     2022-05-09    2   7500   850       1 out of 2  Carpet Area   
...          ...  ...    ...   ...              ...          ...   
4741  2022-05-18    2  15000  1000       3 out of 5  Carpet Area   
4742  2022-05-15    3  29000  2000       1 out of 4   Super Area   
4743  2022-07-10    3  35000  1750       3 out of 5  Carpet Area   
4744  2022-07-06    3  45000  1500     23 out of 34  Carpet Area   
4745  2022-05-04    2  15000  1000       4 out of 5  Carpet Area   

                 Area Locality       City Furnishing Status  Tenant Preferred  \
0                       Bandel    Kolkata       Unfurnished  Bachelors/Family   
1     Phool Bagan, Kankurgachi    Kolkata    Semi-Furnished  Bachelors/Family   
2      Salt Lake City Sector 2    Kolkata    Semi-Furnished  Bachelors/Family   
3                  Dumdum Park    Kolkata       Unfurnished  Bachelors/Family   
4                South Dum Dum    Kolkata       Unfurnished         Bachelors   
...                        ...        ...               ...               ...   
4741              Bandam Kommu  Hyderabad    Semi-Furnished  Bachelors/Family   
4742      Manikonda, Hyderabad  Hyderabad    Semi-Furnished  Bachelors/Family   
4743      Himayath Nagar, NH 7  Hyderabad    Semi-Furnished  Bachelors/Family   
4744                Gachibowli  Hyderabad    Semi-Furnished            Family   
4745           Suchitra Circle  Hyderabad       Unfurnished         Bachelors   

      Bathroom Point of Contact  
0            2    Contact Owner  
1            1    Contact Owner  
2            1    Contact Owner  
3            1    Contact Owner  
4            1    Contact Owner  
...        ...              ...  
4741         2    Contact Owner  
4742         3    Contact Owner  
4743         3    Contact Agent  
4744         2    Contact Agent  
4745         2    Contact Owner  

[4746 rows x 12 columns]

In [5]:
df = df.drop(['Posted On','Tenant Preferred','Area Locality','City','Floor'],axis = 1)
df.head()

BHK   Rent  Size    Area Type Furnishing Status  Bathroom Point of Contact
0    2  10000  1100   Super Area       Unfurnished         2    Contact Owner
1    2  20000   800   Super Area    Semi-Furnished         1    Contact Owner
2    2  17000  1000   Super Area    Semi-Furnished         1    Contact Owner
3    2  10000   800   Super Area       Unfurnished         1    Contact Owner
4    2   7500   850  Carpet Area       Unfurnished         1    Contact Owner

In [6]:
x = df.drop(['Rent'],axis=1)
y=df['Rent']

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3)
x_train

BHK  Size    Area Type Furnishing Status  Bathroom Point of Contact
3260    2   850   Super Area       Unfurnished         2    Contact Owner
155     2   700   Super Area       Unfurnished         2    Contact Owner
3228    2  1125   Super Area    Semi-Furnished         2    Contact Owner
1080    3  1233  Carpet Area    Semi-Furnished         4    Contact Agent
1476    4  2880  Carpet Area       Unfurnished         5    Contact Agent
...   ...   ...          ...               ...       ...              ...
3       2   800   Super Area       Unfurnished         1    Contact Owner
306     1   500   Super Area    Semi-Furnished         1    Contact Owner
4375    2  1200   Super Area       Unfurnished         2    Contact Owner
3047    3  1540  Carpet Area         Furnished         2    Contact Owner
806     1   600   Super Area    Semi-Furnished         1    Contact Owner

[3322 rows x 6 columns]

In [9]:
x_train_1 = x_train.drop(['BHK','Size','Bathroom'],axis=1)

In [10]:
x_test_1 = x_test.drop(['BHK','Size','Bathroom'],axis=1)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder 

In [12]:
trf = ColumnTransformer(transformers=
    [('Area Type',OrdinalEncoder(categories=[["Built Area","Carpet Area","Super Area"]]),["Area Type"]),
     ('Furnishing Status',OrdinalEncoder(categories=[["Unfurnished","Semi-Furnished","Furnished"]]),["Furnishing Status"]),
     ('Point of Contact',OrdinalEncoder(categories=[["Contact Builder","Contact Agent","Contact Owner"]]),["Point of Contact"])],
     remainder='passthrough')

In [13]:
oe = OrdinalEncoder (categories=[["Built Area","Carpet Area","Super Area"],
                                 ["Unfurnished","Semi-Furnished","Furnished"],["Contact Builder","Contact Agent","Contact Owner"]]) 

In [14]:
# np.reshape(oe,(3,3))

In [15]:
# oe = OrdinalEncoder (categories=[["Built Area","Carpet Area","Super Area"]]) 

In [16]:
oe.fit(x_train_1)

OrdinalEncoder(categories=[['Built Area', 'Carpet Area', 'Super Area'],
                           ['Unfurnished', 'Semi-Furnished', 'Furnished'],
                           ['Contact Builder', 'Contact Agent',
                            'Contact Owner']])

In [17]:
oe.transform(x_train_1)

array([[2., 0., 2.],
       [2., 0., 2.],
       [2., 1., 2.],
       ...,
       [2., 0., 2.],
       [1., 2., 2.],
       [2., 1., 2.]])

In [18]:
trf.fit(x_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('Area Type',
                                 OrdinalEncoder(categories=[['Built Area',
                                                             'Carpet Area',
                                                             'Super Area']]),
                                 ['Area Type']),
                                ('Furnishing Status',
                                 OrdinalEncoder(categories=[['Unfurnished',
                                                             'Semi-Furnished',
                                                             'Furnished']]),
                                 ['Furnishing Status']),
                                ('Point of Contact',
                                 OrdinalEncoder(categories=[['Contact Builder',
                                                             'Contact Agent',
                                                             'Contact Owner']]),
                                 ['Point of Contact'])])

In [19]:
x_train_trans = trf.fit_transform(x_train)

In [20]:
x_train_trans 

array([[2.000e+00, 0.000e+00, 2.000e+00, 2.000e+00, 8.500e+02, 2.000e+00],
       [2.000e+00, 0.000e+00, 2.000e+00, 2.000e+00, 7.000e+02, 2.000e+00],
       [2.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 1.125e+03, 2.000e+00],
       ...,
       [2.000e+00, 0.000e+00, 2.000e+00, 2.000e+00, 1.200e+03, 2.000e+00],
       [1.000e+00, 2.000e+00, 2.000e+00, 3.000e+00, 1.540e+03, 2.000e+00],
       [2.000e+00, 1.000e+00, 2.000e+00, 1.000e+00, 6.000e+02, 1.000e+00]])

In [21]:
x_test_trans = trf.fit_transform(x_test)

In [22]:
x_test_trans 

array([[1.000e+00, 1.000e+00, 1.000e+00, 5.000e+00, 3.000e+03, 5.000e+00],
       [1.000e+00, 0.000e+00, 1.000e+00, 2.000e+00, 9.000e+02, 2.000e+00],
       [2.000e+00, 2.000e+00, 2.000e+00, 1.000e+00, 5.650e+02, 2.000e+00],
       ...,
       [1.000e+00, 1.000e+00, 1.000e+00, 3.000e+00, 1.496e+03, 2.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 3.000e+00, 1.750e+03, 4.000e+00],
       [2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 6.700e+02, 2.000e+00]])

In [23]:
import xgboost as xgb 
from sklearn.metrics import mean_absolute_error , r2_score

In [24]:
regr = xgb.XGBRegressor(tree_method = 'hist' , eval_metric = mean_absolute_error )

In [25]:
regr.fit(x_train_trans,y_train,eval_set=[(x_train_trans,y_train)])

[0]	validation_0-rmse:72505.25348	validation_0-mean_absolute_error:25175.61523
[1]	validation_0-rmse:65299.76971	validation_0-mean_absolute_error:21026.70117
[2]	validation_0-rmse:60485.83070	validation_0-mean_absolute_error:18472.03125
[3]	validation_0-rmse:57448.22242	validation_0-mean_absolute_error:16858.62695
[4]	validation_0-rmse:55567.07019	validation_0-mean_absolute_error:15878.01758
[5]	validation_0-rmse:54069.27251	validation_0-mean_absolute_error:15258.26367
[6]	validation_0-rmse:53116.65272	validation_0-mean_absolute_error:14891.52637
[7]	validation_0-rmse:52437.49361	validation_0-mean_absolute_error:14566.74023
[8]	validation_0-rmse:52047.83261	validation_0-mean_absolute_error:14309.27637
[9]	validation_0-rmse:51671.97051	validation_0-mean_absolute_error:14120.18945
[10]	validation_0-rmse:51353.92991	validation_0-mean_absolute_error:14003.87207
[11]	validation_0-rmse:51020.42903	validation_0-mean_absolute_error:13809.26465
[12]	validation_0-rmse:50827.68463	validation_0-me

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False,
             eval_metric=<function mean_absolute_error at 0x000002023A757420>,
             feature_types=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [26]:
y_predict = regr.predict(x_test_trans) 

In [27]:
mean_absolute_error(y_test,y_predict)

17649.5997496187

In [28]:
r2_score(y_test,y_predict)

0.06180322779566583