In [1]:
import numpy as np

In [4]:
y=np.array([1,2,3,4,5])
y.ndim #tp find out dimension 

1

In [7]:
y = np.array([[1,2,3,4,5],[1,2,3,4,5]])
y

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [11]:
x=np.array([1,2,3,4,5],ndmin=10) #used to set the dimension of an array 
x.ndim

10

In [12]:
#zeros 
x=np.zeros(4)
x

array([0., 0., 0., 0.])

In [15]:
x= np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

In [17]:
x=np.empty(4)
x

array([1., 1., 1., 1.])

In [21]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
y=np.eye(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
b=np.linspace(2,90,19)
b

array([ 2.        ,  6.88888889, 11.77777778, 16.66666667, 21.55555556,
       26.44444444, 31.33333333, 36.22222222, 41.11111111, 46.        ,
       50.88888889, 55.77777778, 60.66666667, 65.55555556, 70.44444444,
       75.33333333, 80.22222222, 85.11111111, 90.        ])

In [26]:
#RANDOM
var = np.random.rand(3)
var

array([0.43499218, 0.73606842, 0.94302686])

In [28]:
 var = np.random.randn(2,4)
var

array([[ 1.0448782 ,  1.36470025,  0.33491811, -0.38080543],
       [ 1.56691099,  1.4399358 , -1.12321438,  0.85265532]])

In [97]:
var = np.random.ranf(4)
var

array([0.84687521, 0.71280201, 0.39582698, 0.29801742])

In [34]:
var = np.random.randint(1,9,5)
var

array([1, 5, 6, 5, 6])

In [44]:
#DATA TYPE 
a = np.array([1,2,3,4,5,6,7,"A","B","C"])
print(a.dtype)
a

<U11


array(['1', '2', '3', '4', '5', '6', '7', 'A', 'B', 'C'], dtype='<U11')

In [43]:
a = np.array([1,2,3,4,5,6,7],dtype ='f')
print(a.dtype)
a

float32


array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [47]:
a = np.array([1,2,3,4,5])
b=a.astype(int)
b.dtype

dtype('int32')

In [54]:
#SHAPE
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print()
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]

(2, 4)


In [64]:
#RESHAPE
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var.ndim)
y=var.reshape(2,3,2)
v=var.reshape(4,3)
print(v)
print(v.ndim)
print(y)
y.ndim

1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


3

In [66]:
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var.ndim)
y=var.reshape(2,3,2)
v=var.reshape(4,3)
print(v)
print(v.ndim)
print(y)
y.ndim
print()

#reshaping into 1 dimension
b=y.reshape(-1)
print(b)
print(b.ndim)

1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [73]:
#ARITHMETIC
var = np.array([1,2,3,4])
var1 = np.array([1,2,3,4])
varadd = np.add(var,var1)
varadd

array([2, 4, 6, 8])

In [74]:
var = np.array([1,2,3,4])
var1 = np.array([1,2,3,4])
varadd = np.subtract(var,9)
varadd

array([-8, -7, -6, -5])

In [77]:
var = np.array([1,2,3,4])
var1 = np.array([1,2,3,4])
varadd = np.mod(var,3)
varadd

array([1, 2, 0, 1], dtype=int32)

In [78]:
var = np.array([1,2,3,4])
var1 = np.array([1,2,3,4])
varadd = np.reciprocal(var)
varadd

array([1, 0, 0, 0])

In [79]:
var = np.array([[1,2,3,4],[5,6,7,8]])
var1 = np.array([[1,2,3,4],[5,6,7,8]])
# var1 = np.array([1,2,3,4])
varadd = np.add(var,var1)
varadd

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [84]:
var = np.array([[9,8,7,6,5,4,3,2]])
print(var.min(),var.argmin())
print(var.max(),var.argmax())

2 7
9 0


In [94]:
var = np.array([[9,8,7,6],[5,4,3,2]])
print(np.min(var,axis=0)) #0 for column-wise 1 for row-wise
print(np.min(var,axis=1))
print(np.max(var,axis=0))
print(np.max(var,axis=1))
print(np.sqrt(var))

[5 4 3 2]
[6 2]
[9 8 7 6]
[9 5]
[[3.         2.82842712 2.64575131 2.44948974]
 [2.23606798 2.         1.73205081 1.41421356]]


In [95]:
var = np.array([1,2,3])
print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [99]:
#BROADCASTING ERROR
x=np.array([1,2])
y=np.array([4,5])
print(x+y)

[5 7]


In [102]:
var = np.array([[9,8,7,6],[5,4,3,2]])

print(var[0,3])

6


In [108]:
var = np.array([[[9,8,7,6],[5,4,3,2]],
                [[0,9,8,7],[1,2,3,4]]])
print(var)
print(var[1,1,2])

[[[9 8 7 6]
  [5 4 3 2]]

 [[0 9 8 7]
  [1 2 3 4]]]
3


            #slicing 
            

In [110]:
var = np.array([1,2,3,4,5])
print(var[1:4])

[2 3 4]


In [111]:
var = np.array([[9,8,7,6],[5,4,3,2]])
print(var[0,1:])

[8 7 6]


In [113]:
var = np.array([[[9,8,7,6],[5,4,3,2]],
                [[0,9,8,7],[1,2,3,4]]])
print(var)
print(var[0,1,1:])

[[[9 8 7 6]
  [5 4 3 2]]

 [[0 9 8 7]
  [1 2 3 4]]]
[4 3 2]


In [114]:
x= np.array([1,2,3,4,5,6,7])
for i in x:
    print(i)

1
2
3
4
5
6
7


In [117]:
b = np.array([[1,2,3,4],[5,6,7,8]])
for i in b:
    print(i)

print()

for i in b:
    # print(i)
    for z in i :
        print(z)

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [124]:
var = np.array([[[9,8,7,6],[5,4,3,2]],
                [[0,9,8,7],[1,2,3,4]]])

# for a in var :
#     for b in a :
#         for c in b:
#             print(c) 

for i in np.nditer(var):
    print(i)

print()

for i in np.ndenumerate(var):
    print(i)

9
8
7
6
5
4
3
2
0
9
8
7
1
2
3
4

((0, 0, 0), 9)
((0, 0, 1), 8)
((0, 0, 2), 7)
((0, 0, 3), 6)
((0, 1, 0), 5)
((0, 1, 1), 4)
((0, 1, 2), 3)
((0, 1, 3), 2)
((1, 0, 0), 0)
((1, 0, 1), 9)
((1, 0, 2), 8)
((1, 0, 3), 7)
((1, 1, 0), 1)
((1, 1, 1), 2)
((1, 1, 2), 3)
((1, 1, 3), 4)


In [128]:
var = np.array([[9,8,7,6],[5,4,3,2]])

v = var.copy()
y = var.view()
print(y)
v

[[9 8 7 6]
 [5 4 3 2]]


array([[9, 8, 7, 6],
       [5, 4, 3, 2]])

In [130]:
x = [1,5,8,4]
y=[2,5,8,2]

z=np.concatenate((x,y))
z

array([1, 5, 8, 4, 2, 5, 8, 2])

In [131]:
x=[1,4,7,2,75,92,4,8,2,4,5]
np.sort(x)

array([ 1,  2,  2,  4,  4,  4,  5,  7,  8, 75, 92])

In [134]:
x = np.array([1,2,3,4,5,6])
x.shape

(6,)

In [137]:
new = x[np.newaxis , :]
new.shape

(1, 6)

In [138]:
new1=x[:,np.newaxis]
new1.shape

(6, 1)

In [141]:
row = np.expand_dims(x,axis=0)
row.shape

(1, 6)

In [142]:
col = np.expand_dims(y,axis=1)
col.shape

(4, 1)

In [154]:
x = np.array([[1,2,3,4],[5,6,7,8],[0,9,8,7]])
print(x)
five_up = (x >= 5)
print(x[five_up])

[[1 2 3 4]
 [5 6 7 8]
 [0 9 8 7]]
[5 6 7 8 9 8 7]


In [155]:
y = np.array([1,2,3,4,5,6,7,8,9,0,11,12,13,14,15,16])
y
z = np.array_split(y,4)
z 

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9,  0, 11, 12]),
 array([13, 14, 15, 16])]

In [156]:
k = x.transpose()
k

array([[1, 5, 0],
       [2, 6, 9],
       [3, 7, 8],
       [4, 8, 7]])

In [167]:
q=np.flip(y)
print(q)
m=np.flip(x)
m

[16 15 14 13 12 11  0  9  8  7  6  5  4  3  2  1]


array([[7, 8, 9, 0],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])